name: Information
version: 0.3
authors: [lst96, Hodgetts330]
main: io.github.lst96.Information.Information
commands:
  Website: 
      description: Displays your Website link.   
  Donate:
      description: Displays donation link.  
  Vote:
      description: Displays voting link.  
  Inforeload:
      description: Reloads Configuration.   
  Staff:
     description: Displays staff. 
  Rules:
    description: Displays rules.
    
 permissions:
   information.website:
   description: Gives permission to website command. 
   default: op
     
    