name: Information
version: 1.1
author: lst96
main: io.github.lst96.Information.Information
commands:
  website: 
      description: Displays your Website link.
      aliases: [infowebsite]
  Donate:
      description: Displays donation link.
      aliases: [infodonate]
  Vote:
      description: Displays voting link.
      aliases: [infovote]
  Inforeload:
      description: Reloads Configuration. 
      aliases: []
  Staff:
      description: Displays staff. 
      aliases: [infostaff]
  Rules:
      description: Displays rules.
      aliases: [inforules]
  Ram:
      description: Displays Ram usage.
      aliases: [inforam]
  Motd:
      description: Displays Motd.
      aliases: [infomotd]
  Online:
      description: Displays online players.
      aliases: [infoonline]
  Ip:
      description: Displays Server Ip.
      aliases: [infoip]
  Player:
      description: Displays player info.
      aliases: [infoplayer]
  Twitter:
      description: Displays twitter link.
      aliases: [infotwitter]
  Facebook:
      description: Displays facebook link.
      aliases: [infofacebook]
  Einfo:
      description: Displays Extra Information about the server.
      aliases: []
  Youtube:
      description: Displays youtube link.
      aliases: [infoyoutube]
  Stats:
      description: Displays Stats about the server.   
      aliases: [infostats]
  SetVote:
      description: Adds voting links.
      aliases: [infosetvote]
  DelVote:
      description: Deletes voting links.
      aliases: [infodelvote]
  ViewVote:
      description: Views currently set voting links.
      aliases: [infoviewvote]
permissions:
    information.*:
        description: Gives access to all information commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: true
            information.staff: true
            information.rules: true
            information.ram: true
            information.online: true
            information.ip: true
            information.player: true
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: true
            inforamtion.setvote: true
            information.delvote: true
            information.viewvote: true
    information.member:
        description: Gives access to member commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: false
            information.staff: true
            information.ram: false
            information.online: false
            information.ip: true
            information.player: false
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: false
            information.setvote: false
            information.delvote: false
            information.viewvote: true
    information.admin:
        description: Gives access to admin commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: false
            information.staff: true
            information.rules: true
            information.ram: true
            information.online: true
            information.ip: true
            information.player: true
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: true
            information.setvote: true
            information.delvote: true
            information.viewvote: true
    information.website:
        description: Allows use of website command.
    information.donate:
        description: Allows use of donate command.
    information.vote:
        description: Allows use of vote command.
    information.reload:
        description: Allows use of inforeload command.
    information.staff:
        description: Allows use of staff command.
    information.rules:
        description: Allows use of rules command.
    information.ram:
        description: Allows use of ram command.
    information.online:
        description: Allows use of online command.
    information.motd:
        description: Allows use of motd command.
    information.ip:
        description: Allows use of ip command.
    information.player:
        description: Allows use of player command.
    information.twitter:
        description: Allows use of twitter command.
    information.facebook:
        description: Allows use of facebook command.
    information.extra:
        description: Allows use of Einfo command.
    information.youtube:
        description: Allows use of youtube command.    
    information.stats:
       description: Allows use of stats command.
    information.setvote:
       description: Allows use of setvote command.
    information.delvote:
       description: Allows use of delvote command.
    information.viewvote:
       description: Allows use of viewvote command.
    