name: Information
version: 1.3
author: lst96
main: io.github.lst96.Information.Information
commands:
  website: 
      description: Displays your Website link.
      aliases: [infowebsite]
  Donate:
      description: Displays donation link.
      aliases: [infodonate]
  Vote:
      description: Displays voting link.
      aliases: [infovote]
  Inforeload:
      description: Reloads Configuration. 
      aliases: []
  Staff:
      description: Displays staff. 
      aliases: [infostaff]
  Rules:
      description: Displays rules.
      aliases: [inforules]
  Ram:
      description: Displays Ram usage.
      aliases: [inforam]
  Motd:
      description: Displays Motd.
      aliases: [infomotd]
  Online:
      description: Displays online players.
      aliases: [infoonline]
  Ip:
      description: Displays Server Ip.
      aliases: [infoip]
  Player:
      description: Displays player info.
      aliases: [infoplayer]
  Twitter:
      description: Displays twitter link.
      aliases: [infotwitter]
  Facebook:
      description: Displays facebook link.
      aliases: [infofacebook]
  Einfo:
      description: Displays Extra Information about the server.
      aliases: []
  Youtube:
      description: Displays youtube link.
      aliases: [infoyoutube]
  Stats:
      description: Displays Stats about the server.   
      aliases: [infostats]
  SetVote:
      description: Adds voting links.
      aliases: [infosetvote]
  DelVote:
      description: Deletes voting links.
      aliases: [infodelvote]
permissions:
    information.*:
        description: Gives access to all information commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: true
            information.staff: true
            information.rules: true
            information.ram: true
            information.online: true
            information.ip: true
            information.player: true
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: true
            inforamtion.setvote: true
            information.delvote: true
    information.member:
        description: Gives access to member commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: false
            information.staff: true
            information.ram: false
            information.online: false
            information.ip: true
            information.player: false
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: false
            information.setvote: false
            information.delvote: false
    information.admin:
        description: Gives access to admin commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: false
            information.staff: true
            information.rules: true
            information.ram: true
            information.online: true
            information.ip: true
            information.player: true
            information.twitter: true
            information.facebook: true
            information.extra: true
            information.youtube: true
            information.stats: true
            information.setvote: true
            information.delvote: true
    