name: Information
version: 0.3
authors: [lst96, Hodgetts330]
main: io.github.lst96.Information.Information
commands:
  Website: 
      description: Displays your Website link.   
  Donate:
      description: Displays donation link.  
  Vote:
      description: Displays voting link.  
  Inforeload:
      description: Reloads Configuration.   
  Staff:
      description: Displays staff. 
  Rules:
      description: Displays rules.
    
permissions:
    information.*:
        description: Gives access to all information commands
        children:
            information.website: true
            information.donate: true
            information.vote: true
            information.reload: true
            information.staff: true
            information.rules: true
    information.website:
        description: Allows use of website command
        default: op
    information.donate:
        description: Allows use of donate command
        default: op
    information.vote:
        description: Allows use of vote command
        default: op
    information.reload:
        description: Allows use of inforeload command
        default: op
    information.staff:
        description: Allows use of staff command
        default: op
    information.rules:
        description: Allows use of rules command
        default: op
        
    